### ISSUE TITLE
Inquiry about the underlying knowledge and technique

### ISSUE THREAD

**Issue by AbbyYangbb** [fubel/PeronaMalikDiffusion#1]
Hi fubel, 

Thank you very much for sharing the code! I am quite impressed by what Perona-Malik Diffusion can achieve with your code, but I am also curious about the knowledge behind it and would like to know more about how your code works. 

Could you kindly give me some suggestions on understanding your code? Maybe some articles or term that I am supposed to investigate. I really appreciate your help! 

Thanks,
Bingbin

**Comment by fubel** [comment]
Hi Bingbin,

thanks for your message. The code is essentially just a discretization of the anisotropic diffusion:
https://en.wikipedia.org/wiki/Anisotropic_diffusion#Formal_definition 

There are different ways for discretization. I'm not sure which version I used because it's been quite a while since I wrote the code. There are plenty of ways, e.g. http://students.mimuw.edu.pl/~mwielgus/files/PM_equation.pdf

In the code, I did a simpler strategy and basically use the difference windows to compute the divergence and then avoid the integration by summing up some terms.

There's a very nice book by Joachim Weickert on anisotropic filters, you can find the full text with Google I believe. I hope this helps you a little bit. But feel free to ask me more questions :)

**Comment by AbbyYangbb** [comment]
Hi fubel! I am sorry for the late reply. Thank you very much for the information! I really appreciate your explanation, and I also read the according wiki page. They do help me a lot to understand the 
 fundamentals behind your code. Thank you!
